<div style="width:595.3pt;margin-bottom:72.0pt;margin-top:72.0pt;margin-left:90.0pt;margin-right:90.0pt;"><p
        style="text-align:center;white-space:pre-wrap;"><span
        style="font-size:22.0pt;font-weight:bold;color:#000000;white-space:pre-wrap;">天津市居住证积分受理通知书</span></p>
    <p style="text-align:right;white-space:pre-wrap;"><span
            style="font-family:'Cambria';font-size:22.0pt;font-weight:bold;color:#000000;white-space:pre-wrap;">No. </span><span
            style="font-family:'Cambria';font-size:22.0pt;font-weight:bold;color:#000000;white-space:pre-wrap;">${person.acceptNumber}</span><span
            style="font-family:'Cambria';font-size:22.0pt;font-weight:bold;color:#000000;white-space:pre-wrap;">           </span>
    </p>
    <p style="text-align:left;white-space:pre-wrap;"><span
            style="font-family:'Cambria';font-size:16.0pt;font-weight:bold;color:#000000;text-decoration:underline;white-space:pre-wrap;">${company.companyName}</span><span
            style="font-family:'Cambria';font-size:16.0pt;font-weight:bold;color:#000000;text-decoration:underline;white-space:pre-wrap;">：</span>
    </p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">你单位</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${year}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">年</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${month}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">月</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${day}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">日提交的本单位职工</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${person.name}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">同志的积分申请，经审核，予以受理。</span>
    </p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">用人单位应当在积分服务窗口受理申请后即时将需要提交的材料分送至负责积分审核的各相关部门服务窗口，因特殊情况不能即时送审的，应在3个工作日内送达，逾期不再受理。</span>
    </p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">特此通知。</span></p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><br/></p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><br/></p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><br/></p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><br/></p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><br/></p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><br/></p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><br/></p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><br/></p>
    <p style="text-indent:32.0pt;text-align:left;white-space:pre-wrap;"><br/></p>
    <p style="text-indent:32.0pt;text-align:right;white-space:pre-wrap;"><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${nowYear}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">年</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${nowMonth}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">月</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${nowDay}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">日  </span></p>
    <p style="text-align:left;white-space:pre-wrap;"><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">受理部门：</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${department}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">     </span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">   </span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">    </span><span
            id="_GoBack"/><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">受理人：</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">  </span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">   </span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${user.displayName}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">   </span>
    </p>
    <p style="text-align:left;white-space:pre-wrap;"><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">受理时间：</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${now}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">   </span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;"> </span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">    </span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">  </span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">联系电话</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;white-space:pre-wrap;">：</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;"> </span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">${user.contactPhone}</span><span
            style="font-family:'Cambria';font-size:16.0pt;color:#000000;text-decoration:underline;white-space:pre-wrap;">            </span>
    </p></div>
