<table style="font-size: 14px;" class="table table-scrollable table-striped table-bordered table-hover dataTable no-footer">
    <tr>
        <th class=""></th>
        <th>全市</th>
        <th>市区</th>
        <th>滨海新区</th>
    </tr>
    <tr>
        <td>已在系统注册人数</td>
        <td>${registerSum}</td>
        <td>${registerSum_1}</td>
        <td>${registerSum_2}</td>
    </tr>
    <tr>
        <td>已通过自助测评人数</td>
        <td>${passSeltTest}</td>
        <td>${passSeltTest_1}</td>
        <td>${passSeltTest_2}</td>
    </tr>
    <tr>
        <td>已申请网上预审的人数</td>
        <td>${applyingInterPre}</td>
        <td>${applyingInterPre_1}</td>
        <td>${applyingInterPre_2}</td>
    </tr>
    <tr>
        <td>已通过网上预审的人数</td>
        <td>${applyedInterPre}</td>
        <td>${applyedInterPre_1}</td>
        <td>${applyedInterPre_2}</td>
    </tr>
    <tr>
        <td>已预约的人数</td>
        <td>${reservationSum}</td>
        <td>${reservationSum_1}</td>
        <td>${reservationSum_2}</td>
    </tr>
    <tr>
        <td>人社受理审核通过的人数</td>
        <td>${acceptedCheck}</td>
        <td>${acceptedCheck_1}</td>
        <td>${acceptedCheck_2}</td>
    </tr>
    <tr>
        <td>人社、公安审核都通过的人数</td>
        <td>${acceptedCheckRensheGongan}</td>
        <td>${acceptedCheckRensheGongan_1}</td>
        <td>${acceptedCheckRensheGongan_2}</td>
    </tr>
    <tr>
        <td>人社、公安任一部门审核都未通过的人数</td>
        <td>${fieldPassGonganAndRenshe}</td>
        <td>${fieldPassGonganAndRenshe_1}</td>
        <td>${fieldPassGonganAndRenshe_2}</td>
    </tr>
    <tr>
        <td>人社受理审核待审核人数</td>
        <td>${renshePassing}</td>
        <td>${renshePassing_1}</td>
        <td>${renshePassing_2}</td>
    </tr>
</table>