package com.orange.score.module.score.ws;

public class SOAP2Response {

    public static void main(String[] args) {
        String soapResponse =
                "<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">" + "   <soap:Body>"
                        + "<ns1:RsResidentJFRDBusinessRevResponse xmlns:ns1=\"http://service.webinterface.yzym.si.sl.neusoft.com/\">"
                        + "<return xmlns=\"http://service.webinterface.yzym.si.sl.neusoft.com/\"><![CDATA[" + "<ROOT>"
                        + "<appCode>0</appCode>" + "<birthIns></birthIns>"
                        + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>" + "<injuryIns></injuryIns>"
                        + "<medicalIns></medicalIns>" + "<payBase></payBase>" + "<paymentYear>201701</paymentYear>"
                        + "<pesionIns></pesionIns>" + "<personNumber>1001080631</personNumber>"
                        + "<unemploymentIns></unemploymentIns>" + "<unitCode></unitCode>" + "<unitName></unitName>"
                        + "<unitNumber></unitNumber>" + "</ROOT>" + "<ROOT>" + "<appCode>0</appCode>"
                        + "<birthIns></birthIns>" + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>"
                        + "<injuryIns></injuryIns>" + "<medicalIns></medicalIns>" + "<payBase></payBase>"
                        + "<paymentYear>201702</paymentYear>" + "<pesionIns></pesionIns>"
                        + "<personNumber>1001080631</personNumber>" + "<unemploymentIns></unemploymentIns>"
                        + "<unitCode></unitCode>" + "<unitName></unitName>" + "<unitNumber></unitNumber>" + "</ROOT>"
                        + "<ROOT>" + "<appCode>0</appCode>" + "<birthIns></birthIns>"
                        + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>" + "<injuryIns></injuryIns>"
                        + "<medicalIns></medicalIns>" + "<payBase></payBase>" + "<paymentYear>201703</paymentYear>"
                        + "<pesionIns></pesionIns>" + "<personNumber>1001080631</personNumber>"
                        + "<unemploymentIns></unemploymentIns>" + "<unitCode></unitCode>" + "<unitName></unitName>"
                        + "<unitNumber></unitNumber>" + "</ROOT>" + "<ROOT>" + "<appCode>0</appCode>"
                        + "<birthIns></birthIns>" + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>"
                        + "<injuryIns></injuryIns>" + "<medicalIns></medicalIns>" + "<payBase></payBase>"
                        + "<paymentYear>201704</paymentYear>" + "<pesionIns></pesionIns>"
                        + "<personNumber>1001080631</personNumber>" + "<unemploymentIns></unemploymentIns>"
                        + "<unitCode></unitCode>" + "<unitName></unitName>" + "<unitNumber></unitNumber>" + "</ROOT>"
                        + "<ROOT>" + "<appCode>0</appCode>" + "<birthIns></birthIns>"
                        + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>" + "<injuryIns></injuryIns>"
                        + "<medicalIns></medicalIns>" + "<payBase></payBase>" + "<paymentYear>201705</paymentYear>"
                        + "<pesionIns></pesionIns>" + "<personNumber>1001080631</personNumber>"
                        + "<unemploymentIns></unemploymentIns>" + "<unitCode></unitCode>" + "<unitName></unitName>"
                        + "<unitNumber></unitNumber>" + "</ROOT>" + "<ROOT>" + "<appCode>0</appCode>"
                        + "<birthIns></birthIns>" + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>"
                        + "<injuryIns></injuryIns>" + "<medicalIns></medicalIns>" + "<payBase></payBase>"
                        + "<paymentYear>201706</paymentYear>" + "<pesionIns></pesionIns>"
                        + "<personNumber>1001080631</personNumber>" + "<unemploymentIns></unemploymentIns>"
                        + "<unitCode></unitCode>" + "<unitName></unitName>" + "<unitNumber></unitNumber>" + "</ROOT>"
                        + "<ROOT>" + "<appCode>0</appCode>" + "<birthIns></birthIns>"
                        + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>" + "<injuryIns></injuryIns>"
                        + "<medicalIns></medicalIns>" + "<payBase></payBase>" + "<paymentYear>201707</paymentYear>"
                        + "<pesionIns></pesionIns>" + "<personNumber>1001080631</personNumber>"
                        + "<unemploymentIns></unemploymentIns>" + "<unitCode></unitCode>" + "<unitName></unitName>"
                        + "<unitNumber></unitNumber>" + "</ROOT>" + "<ROOT>" + "<appCode>0</appCode>"
                        + "<birthIns></birthIns>" + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>"
                        + "<injuryIns></injuryIns>" + "<medicalIns></medicalIns>" + "<payBase></payBase>"
                        + "<paymentYear>201708</paymentYear>" + "<pesionIns></pesionIns>"
                        + "<personNumber>1001080631</personNumber>" + "<unemploymentIns></unemploymentIns>"
                        + "<unitCode></unitCode>" + "<unitName></unitName>" + "<unitNumber></unitNumber>" + "</ROOT>"
                        + "<ROOT>" + "<appCode>0</appCode>" + "<birthIns></birthIns>"
                        + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>" + "<injuryIns></injuryIns>"
                        + "<medicalIns></medicalIns>" + "<payBase></payBase>" + "<paymentYear>201709</paymentYear>"
                        + "<pesionIns></pesionIns>" + "<personNumber>1001080631</personNumber>"
                        + "<unemploymentIns></unemploymentIns>" + "<unitCode></unitCode>" + "<unitName></unitName>"
                        + "<unitNumber></unitNumber>" + "</ROOT>" + "<ROOT>" + "<appCode>0</appCode>"
                        + "<birthIns></birthIns>" + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>"
                        + "<injuryIns></injuryIns>" + "<medicalIns></medicalIns>" + "<payBase></payBase>"
                        + "<paymentYear>201710</paymentYear>" + "<pesionIns></pesionIns>"
                        + "<personNumber>1001080631</personNumber>" + "<unemploymentIns></unemploymentIns>"
                        + "<unitCode></unitCode>" + "<unitName></unitName>" + "<unitNumber></unitNumber>" + "</ROOT>"
                        + "<ROOT>" + "<appCode>0</appCode>" + "<birthIns></birthIns>"
                        + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>" + "<injuryIns></injuryIns>"
                        + "<medicalIns></medicalIns>" + "<payBase></payBase>" + "<paymentYear>201711</paymentYear>"
                        + "<pesionIns></pesionIns>" + "<personNumber>1001080631</personNumber>"
                        + "<unemploymentIns></unemploymentIns>" + "<unitCode></unitCode>" + "<unitName></unitName>"
                        + "<unitNumber></unitNumber>" + "</ROOT>" + "<ROOT>" + "<appCode>0</appCode>"
                        + "<birthIns></birthIns>" + "<errMsg>判定期内缴费信息中出现断缴、补缴、个人缴费情况，请予核实</errMsg>" + "<flag>2</flag>"
                        + "<injuryIns></injuryIns>" + "<medicalIns></medicalIns>" + "<payBase></payBase>"
                        + "<paymentYear>201712</paymentYear>" + "<pesionIns></pesionIns>"
                        + "<personNumber>1001080631</personNumber>" + "<unemploymentIns></unemploymentIns>"
                        + "<unitCode></unitCode>" + "<unitName></unitName>" + "<unitNumber></unitNumber>"
                        + "</ROOT>]]></return>" + "  </ns1:RsResidentJFRDBusinessRevResponse>" + "   </soap:Body>"
                        + "</soap:Envelope>";
        System.out.println(soapResponse.indexOf("<![CDATA["));
        String result = soapResponse
                .substring((soapResponse.indexOf("<![CDATA[") + "<![CDATA[".length()), soapResponse.indexOf("]]>"))
                .replaceAll("<ROOT>", "<br>").replaceAll("</ROOT>", "");
        System.out.println(result);

    }
}
